### PR TITLE
Visual Synth tutorial

### PR DESCRIPTION
**Pull request by msurguy**
@gohai this will be an ongoing PR, please don't merge yet

### CODE REVIEW

**Comment by msurguy** [comment]
@gohai in https://github.com/processing/processing-pi-website/pull/10/commits/874f28682ece883c2ec4f7a01315fbbea852fb50 I'm toying around with a little different header style for the tutorial: shifting the tags + author to the top, making the name of the project a little bigger + lighter, also removing the updated date and putting that as a `title` attribute so that when the text is rolled over, it shows up. 

Here's the new layout: 

screen shot 2018-07-07 at 7 56 27 am

Do you think this is an improvement?

**Comment by gohai** [comment]
@msurguy I think before was better, but removing the edit date is certainly a plus. Would just use spacing, and perhaps a lighter grey for the tags if they are still too prominent to your eyes.

**Comment by gohai** [comment]
@msurguy ready for me to pull?

**Comment by msurguy** [comment]
@gohai all done! 

I've implemented all feedback that you have provided so this should be ready to be merged at your discretion!

**Comment by gohai** [comment]
@msurguy Pulled and uploaded. Good work!

**Pull request merged**
